### ISSUE TITLE
Warning Optimization

### ISSUE THREAD

**Issue by Creeperzito16** [OvernightAU/ModdingUs#3]
Não sei se isso conta como um warn mas. 
Ta mau otimizado e meu celular não é um j5 de 2010, caso consiga otimizar Seria bom, caso contrário nada não já foi quase um ano recriando o jogo...

Eng:
I don't know if that counts as a warn but. 
It's badly optimized and my cell phone is not a j5 from 2010, if you can optimize it would be good, otherwise nothing has not been almost a year recreating the game...

**Comment by Creeperzito16** [comment]
A e por favor lançar para pc
Oh, please create a version to pc

**Comment by Pietrodjaowjao** [comment]
Maybe sometime

**Comment by Pietrodjaowjao** [comment]
I tried to optimize a little bit, not sure if it changed anything. also, the lag normally only happens in submerged.
